version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 18.10.0

  pre_build:
    commands:
      - yarn install

  build:
    commands:
      - yarn build

  post_build:
    commands:
      - rm -rf node_modules

artifacts:
  files:
    - '**/*'
